# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=website.models.get_image_path)),
                ('is_cover_photo', models.BooleanField()),
                ('caption', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='upload',
            name='project',
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Upload',
        ),
        migrations.AddField(
            model_name='photo',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='website.Project'),
        ),
    ]
