# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 17:28
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20170516_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to=website.models.get_image_path),
        ),
    ]
