# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20170522_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=website.models.get_image_path),
        ),
    ]
