# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20170522_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
